data_cfg:
  dataset_name: BRIAR
  dataset_root: /research/iprobe-ashbau12/hpcc_briar/wb_preprocessed/rgb-gtbbox
  dataset_partition: /research/iprobe-ashbau12/repos/outside/OpenGait/partitions/BGC_full_partition.json
  num_workers: 2
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: BRIAR

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 45000
  save_name: Baseline
  eval_func: identification_briar_yiyang
  sampler:
    batch_shuffle: false
    batch_size: 2
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_num_fixed: 500 # fixed frames number for training
    random_sample_full_video: false
    use_full_video: false
  metric: euc # cos
  transform:
    - type: BaseRgbTransform
      img_w: 64
  failure_analysis:
    save_failure_sequences: false
    max_fail_save_sequences: 100
    

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 0.1
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: Baseline
  backbone_cfg:
    in_channels: 3
    layers_cfg: # Layers configuration for automatically model construction
      - BC-64
      - BC-64
      - M
      - BC-128
      - BC-128
      - M
      - BC-256
      - BC-256
      # - M
      # - BC-512
      # - BC-512
    type: Plain
  SeparateFCs:
    in_channels: 256
    out_channels: 256
    parts_num: 31
  SeparateBNNecks:
    class_num: 158
    in_channels: 256
    parts_num: 31
  bin_num:
    - 16
    - 8
    - 4
    - 2
    - 1

optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 20000
    - 40000
  scheduler: MultiStepLR
trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 1000
  save_name: Baseline
  sync_BN: true
  total_iter: 60000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8 # TripletSampler, batch_size[0] indicates Number of Identity
      - 16 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_num_max: 50 # max frames number for unfixed training
    frames_num_min: 25 # min frames number for unfixed traing
    sample_type: fixed_unordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
    use_full_video: true
    random_sample_full_video: false
  transform:
    - type: BaseRgbTransform
      img_w: 64
